version: '3.8'

services:
  db:
    ports:
      - "5432:5432"
    image: postgres:13
    environment:
      POSTGRES_USER: habit_user
      POSTGRES_PASSWORD: habit_pass
      POSTGRES_DB: habit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habit_user -d habit_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://habit_user:habit_pass@db:5432/habit_db
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      API_URL: http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./bot:/app

volumes:
  postgres_data: