"""initial_tables_1

Revision ID: 00b781ff006c
Revises: 63a32f5aa94a
Create Date: 2025-04-26 21:36:18.218123

"""
from alembic import op
import sqlalchemy as sa


# идентификаторы изменений
revision = '00b781ff006c'
down_revision = '63a32f5aa94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###