"""remove_created

Revision ID: 0c622d42c20c
Revises: 90d45beda49b
Create Date: 2025-04-27 06:21:52.193631

"""
from alembic import op
import sqlalchemy as sa


# идентификаторы изменений
revision = '0c622d42c20c'
down_revision = '90d45beda49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'streak')
    # ### end Alembic commands ###