"""fix_created_at_null

Revision ID: 476e1573437b
Revises: 89267620229c
Create Date: 2025-04-26 21:42:08.821276

"""
from alembic import op
import sqlalchemy as sa


# идентификаторы изменений
revision = '476e1573437b'
down_revision = '89267620229c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###