"""initial_tables_2

Revision ID: 89267620229c
Revises: 00b781ff006c
Create Date: 2025-04-26 21:38:50.013671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# идентификаторы изменений
revision = '89267620229c'
down_revision = '00b781ff006c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###