"""remove_created_at_column

Revision ID: 90d45beda49b
Revises: c6c8ea5db408
Create Date: 2025-04-26 21:48:45.398926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# идентификаторы изменений
revision = '90d45beda49b'
down_revision = 'c6c8ea5db408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###